name: workflow 1
on: push


jobs:
    ahmed:
        needs: shdid
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Welcome 
              run: |
                echo "Hello world"
                
            - name: download artifacts
              uses: actions/download-artifact@v4
              with:
                name: artifact
                path: dragon
            
            - name: cat dragon.txt
              run: cat dragon/dragon.txt
            
    shdid:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: script
              run: |
                ls -ltra
                chmod +x .github/workflows/script.sh
                sh .github/workflows/script.sh
            - name: uplaod artifact
              uses: actions/upload-artifact@v4
              with:
                name: artifact
                path: dragon.txt
                retention-days: 1 